import '@/app/_styles/globals.css';

import { poppins } from '@lib/fonts';

import Header from '@components/Header';

export const metadata = {
  title: { template: '%s: One Stop HGV', default: 'One Stop HGV' },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${poppins} bg-primary-600 font-poppins relative -z-10 min-h-screen w-full overflow-x-hidden text-white`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
